package com.example.tvapp

const val PORT = 5005
const val IP = "10.0.0.55"

const val TV_POWER = "ir tv power"
const val TV_CHANNEL_NUM_0 = "ir tv 0"
const val TV_CHANNEL_NUM_1 = "ir tv 1"
const val TV_CHANNEL_NUM_2 = "ir tv 2"
const val TV_CHANNEL_NUM_3 = "ir tv 3"
const val TV_CHANNEL_NUM_4 = "ir tv 4"
const val TV_CHANNEL_NUM_5 = "ir tv 5"
const val TV_CHANNEL_NUM_6 = "ir tv 6"
const val TV_CHANNEL_NUM_7 = "ir tv 7"
const val TV_CHANNEL_NUM_8 = "ir tv 8"
const val TV_CHANNEL_NUM_9 = "ir tv 9"
const val TV_QUESTION_MARK = "ir tv question"
const val TV_CHANNEL_UP = "ir tv ch+"
const val TV_CHANNEL_DOWN = "ir tv ch-"
const val TV_VOLUME_UP = "ir tv vol+"
const val TV_VOLUME_DOWN = "ir tv vol-"
const val TV_YES = "ir tv yes"
const val TV_RETURN = "ir tv return"
const val TV_UP = "ir tv up"
const val TV_DOWN = "ir tv down"
const val TV_LEFT = "ir tv left"
const val TV_RIGHT = "ir tv right"
const val TV_PLUS = "ir tv plus"